spring:
  application:
    name: tanzu-app
  profiles:
    # Last wins : local,prod
    active: local
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  data:
    rest:
      basePath: /api

info:
  app:
    # Reuse declared variable
    name: ${spring.application.name}
    # Retrieve data from pom.xml
    version: "@project.version@"
    # Sample for deployment variable configuration
    profile: ${spring.profiles.active}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

tanzu:
  super-feature:
    enabled: true