spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-tanzu-app
    username: pgappuser
    password: pgappuser
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com:
      tanzu:
        app: DEBUG

# Feature flag sample
tanzu:
  super-feature:
    enabled: false

