spring:
  application:
    name: tanzu-app-web-app
  profiles:
    # Last wins : local,prod
    active: local
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  data:
    rest:
      basePath: /api
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false

server:
  port : 8090

info:
  app:
    # Reuse declared variable
    name: ${spring.application.name}
    # Retrieve data from pom.xml
    version: "@project.version@"
    # Sample for deployment variable configuration
    hello: hello-${spring.profiles.active}

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      wavefront:
        enabled: false

logging:
  level:
    com:
      tanzu:
        app: DEBUG

# https://tanzu.vmware.com/developer/guides/spring-wavefront-gs/
wavefront:
  application:
    name: tanzu-app-${spring.profiles.active}
    service: tanzu-app-vote

# Feature flag sample
tanzu:
  super-feature:
    enabled: true