spring:
  datasource:
    url: jdbc:postgresql://postgres-tanzu-app.prod:5432/postgres-tanzu-app
    username: pgappuser
    password: 
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

# Feature flag sample
tanzu:
  super-feature:
    enabled: true
