spring:
  datasource:
    url: OVERRIDEN
    username: OVERRIDEN
    password: OVERRIDEN
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  metrics:
    export:
      wavefront:
        uri: OVERRIDEN
        api-token: OVERRIDEN

