---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: tanzu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanzu-app
  template:
    metadata:
      labels:
        app: tanzu-app
    spec:
      containers:
        - image: harbor.cpod-devready.az-fkd.cloud-garage.net/tls/tanzu-app@sha256:cb75fbaa2e2ed03d6bb63c592aeceb1149ee31bf1ed2d890c3bc24d269f683f3
          name: app
          resources:
            limits:
              memory: 1Gi
            requests:
              ephemeral-storage: "128Mi"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 60
            periodSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
