apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  namespace: dev
  name: tanzu-app-deploy
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tanzu-app
    apis.apps.tanzu.vmware.com/register-api: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: ssh://git@github.com/beeNotice/tanzu-app
      ref:
        branch: main
  serviceClaims:
    - name: config
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: sample-configuration-claim
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: postgresql-claim
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "prod"
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17.*"
  params:
    - name: api_descriptor
      value:
        type: openapi
        location:
          path: "/v3/api-docs"
        system: default/tanzu-app-system
        owner: default/default-team
        description: "The Tanzu Simple API"
