apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  namespace: dev
  name: tanzu-app-deploy
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "false"
    app.kubernetes.io/part-of: tanzu-app
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: "tanzu-app"
  annotations:
    autoscaling.knative.dev/minScale: "1"
    serviceclaims.supplychain.apps.x-tanzu.vmware.com/extensions: '{"kind":"ServiceClaimsExtension","apiVersion":"supplychain.apps.x-tanzu.vmware.com/v1alpha1","spec":{"serviceClaims":{"db":{"namespace":"postgresql"}}}}'
spec:
  source:
    git:
      url: https://github.com/beeNotice/tanzu-app
      ref:
        branch: main
  serviceClaims:
  - name: db
    ref:
      apiVersion: sql.tanzu.vmware.com/v1
      kind: Postgres
      name: postgres-tanzu-app
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
