apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  namespace: dev
  name: tanzu-app-deploy
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tanzu-app
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: "tanzu-app"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/beeNotice/tanzu-app
      ref:
        branch: main
