apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-app-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-app-web-app
spec:
  source:
    git:
      url: https://github.com/beeNotice/tanzu-app
      ref:
        branch: main